// src/lib/homepage/header/Header.svelte
<script lang="ts">
	import Button from "$lib/button/Button.svelte";
	import Heading from "./Heading.svelte";
	import Logo from "./Logo.svelte";
</script>

<header>
	<Logo />
	<div>
		<Heading />
		<p class="description">
			Aldrig igen behöver du kompromissa med dina drömmar på grund av stress. 
		</p>
		<p class="description">
			Oavsett om vill starta eget, prestera hållbart på jobbet eller ändra livsriktning så kan jag hjälpa dig.
		</p>
		<p class="description">
			Ladda ner den ultimata guidade meditationen för att förändra negativ stress till positiv.
		</p>
		<!-- <a href="/webbinarie" class="button">Registrera dig till nästa webbinarium</a> -->
		<!-- <Button
		onClick={() => {
			window.open(
				"https://calendly.com/markusmattsson/vagledning?utm_medium=hemsida&utm_source=headerstartsida",
				"_blank"
			);
		}}
		>Boka ett vägledningssamtal
		</Button>	 -->
		<Button 
		
		onClick={() => {
			window.open(
				"/mindsetmeditation",
				"_blank"
			);
		}}
		>Förändra stressen på 5 minuter
		</Button>
	</div>
</header>

<style lang="scss">
	@use "../../../styles/breakpoints.scss" as *;

	header {
		background-image: url("/images/road.jpg");
		background-size: cover;
		background-position: center;
		min-height: 80vh;
		width: 100%;
		padding: 16px;
		margin-bottom: var(--spacing-l);

		@media (min-width: $breakpoint-tablet-portrait) {
			padding: 32px;
		}

		@media (min-width: $breakpoint-tablet-landscape) {
			padding: 48px;
		}

		div {
			max-width: var(--max-width);
			margin: 0 auto;
			padding: 3rem 0;
		}
	}

	.description {
		font-weight: 300;
		color: var(--color-white);
		font-size: var(--font-size-m);
		width: fit-content;
		max-width: 35ch;
		margin-bottom: var(--spacing-m);
	}
</style>

// src/components/Homepage/Header/Header.tsx
import React from "react";
import Button from "../../Button";
import Heading from "./Heading";
import Logo from "./Logo";
import styles from "./Header.module.css";

const Header: React.FC = () => {
	const handleButtonClick = () => {
		window.open("/mindsetmeditation", "_blank");
	};

	return (
		<header className={styles.header}>
			<Logo />
			<div className={styles.content}>
				<Heading />
				<p className={styles.description}>
					Aldrig igen behöver du kompromissa med dina drömmar på grund av stress.
				</p>
				<p className={styles.description}>
					Oavsett om vill starta eget, prestera hållbart på jobbet eller ändra livsriktning så kan
					jag hjälpa dig.
				</p>
				<p className={styles.description}>
					Ladda ner den ultimata guidade meditationen för att förändra negativ stress till positiv.
				</p>
				<Button onClick={handleButtonClick}>Förändra stressen på 5 minuter</Button>
			</div>
		</header>
	);
};

export default Header;
