// src/lib/modal/Modal.svelte
<script lang="ts">
	import {createEventDispatcher} from "svelte";
	import {fade} from "svelte/transition";
	import {XIcon} from "svelte-feather-icons";

	export let showModal;
	let modal;
	const dispatch = createEventDispatcher();
	const close = () => dispatch("close");

	function handleKeydown(e: KeyboardEvent) {
		if (e.key === "Escape") {
			close();
			return;
		}

		if (e.key === "Tab") {
			// trap focus
			const nodes = modal.querySelectorAll("*");
			const tabbable = Array.from(nodes).filter(n => n.tabIndex >= 0);

			let index = tabbable.indexOf(document.activeElement);
			if (index === -1 && e.shiftKey) index = 0;

			index += tabbable.length + (e.shiftKey ? -1 : 1);
			index %= tabbable.length;

			tabbable[index].focus();
			e.preventDefault();
		}
	}
</script>

<svelte:window on:keydown={handleKeydown}/>

{#if showModal}
    <div class="modal-background" on:click={close} transition:fade={{duration: 250}}></div>
    <div class="modal" transition:fade bind:this={modal}>
        <button class="close-btn" on:click={close}>
            <span class="screen-reader-text">Stäng fönster</span>
            <XIcon/>
        </button>
        <slot/>
    </div>
{/if}

<style lang="scss">
    .modal-background {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background: rgba(0, 0, 0, 0.75);
        z-index: 1;
    }

    .modal {
        background-color: var(--color-white);
        padding: 32px;
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        border-radius: 16px;
        overflow: auto;
        z-index: 1;
    }

    .close-btn {
        color: rgba(0, 0, 0, 0.5);
        position: absolute;
        top: 16px;
        right: 16px;
        padding: 6px;
        z-index: 2;
        border-radius: 50%;
        background: transparent;
        cursor: pointer;
        transition: all .2s ease-in-out;
        border: none;
        outline: 2px solid transparent;

        &:hover, &:focus {
            color: #000;
            outline: 2px solid #000;
        }
    }
</style>

// src/components/Modal/Modal.tsx
import React, { useEffect, useRef } from "react";
import { X } from "react-feather";
import styles from "./Modal.module.css";

interface ModalProps {
	showModal: boolean;
	onClose: () => void;
	children: React.ReactNode;
}

const Modal: React.FC<ModalProps> = ({ showModal, onClose, children }) => {
	const modalRef = useRef<HTMLDivElement>(null);

	useEffect(() => {
		const handleKeydown = (e: KeyboardEvent) => {
			if (e.key === "Escape") {
				onClose();
				return;
			}

			if (e.key === "Tab" && modalRef.current) {
				// trap focus
				const nodes = modalRef.current.querySelectorAll("*");
				const tabbable = Array.from(nodes).filter((n) => (n as HTMLElement).tabIndex >= 0);

				let index = tabbable.indexOf(document.activeElement as Element);
				if (index === -1 && e.shiftKey) index = 0;

				index += tabbable.length + (e.shiftKey ? -1 : 1);
				index %= tabbable.length;

				(tabbable[index] as HTMLElement).focus();
				e.preventDefault();
			}
		};

		if (showModal) {
			document.addEventListener("keydown", handleKeydown);
		}

		return () => {
			document.removeEventListener("keydown", handleKeydown);
		};
	}, [showModal, onClose]);

	if (!showModal) return null;

	return (
		<>
			<div className={styles.modalBackground} onClick={onClose}></div>
			<div className={styles.modal} ref={modalRef}>
				<button className={styles.closeBtn} onClick={onClose}>
					<span className="screen-reader-text">Stäng fönster</span>
					<X />
				</button>
				{children}
			</div>
		</>
	);
};

export default Modal;
