// src/lib/homepage/testimonials/Testimonials.svelte
<script lang="ts">
	import testimonials from "../../../data/testimonials";
	import { ChevronRightIcon, ChevronLeftIcon } from "svelte-feather-icons";
	import Testimonial from "./Testimonial.svelte";

	const elementWidth = 332;

	$: numToDisplay = 3;
	$: totalWidth = elementWidth * numToDisplay;
	$: windowWidth = 0;
	$: offset = 0;
	$: atStart = offset === 0;
	$: atEnd = offset <= elementWidth * (testimonials.length - numToDisplay) * -1;

	$: {
		if (windowWidth > 1000) {
			numToDisplay = 3;
		} else if (windowWidth > 680) {
			numToDisplay = 2;
		} else {
			numToDisplay = 1;
		}
	}

	enum Direction {
		Left = "left",
		Right = "right"
	}

	function scroll(direction: Direction): void {
		if (direction === Direction.Left && !atStart) {
			offset += elementWidth;
		} else if (direction === Direction.Right && !atEnd) {
			offset -= elementWidth;
		}
	}
</script>

<svelte:window bind:innerWidth={windowWidth} />

<section>
	<h2>Detta säger tidigare kunder..</h2>
	<div class="testimonials-container" style="width: {totalWidth}px;">
		<div class="testimonials" style="transform: translateX({offset}px);">
			{#each testimonials as testimonial}
				<Testimonial {testimonial} />
			{/each}
		</div>
	</div>
	<div class="buttons">
		<button on:click={() => scroll(Direction.Left)} disabled={atStart}>
			<ChevronLeftIcon />
			<span class="screen-reader-text" title="Föregående">Föregående</span>
		</button>
		<button on:click={() => scroll(Direction.Right)} disabled={atEnd}>
			<ChevronRightIcon />
			<span class="screen-reader-text" title="Nästa">Nästa</span>
		</button>
	</div>
</section>

<style lang="scss">
	section {
		margin: var(--spacing-l) 0;
		width: 100%;
		padding: var(--spacing-l);
		background-color: var(--color-primary-dark);
		display: flex;
		flex-direction: column;
		align-items: center;

		h2 {
			color: var(--color-white);
			font-size: var(--font-size-xl);
			margin-bottom: var(--spacing-m);
			text-align: center;
		}

		.testimonials-container {
			overflow: hidden;
		}

		.testimonials {
			display: flex;
			transition: transform 0.4s ease-in-out;
			margin: var(--spacing-m) 0;
		}

		.buttons {
			display: flex;
			gap: 16px;

			button {
				border: none;
				background: transparent;
				color: var(--color-primary-light);
				cursor: pointer;
				transition: ease-in-out 0.25s;

				&:disabled {
					opacity: 0.5;
					cursor: not-allowed;
				}

				&:hover {
					color: var(--color-white);
				}
			}
		}

		.screen-reader-text {
			border: 0;
			clip: rect(1px, 1px, 1px, 1px);
			clip-path: inset(50%);
			height: 1px;
			margin: -1px;
			overflow: hidden;
			padding: 0;
			position: absolute;
			width: 1px;
			word-wrap: normal !important;
		}
	}
</style>

// src/components/Homepage/Testimonials/Testimonials.tsx
import React, { useState, useEffect } from "react";
import { ChevronLeft, ChevronRight } from "react-feather";
import testimonials from "../../../data/testimonials";
import Testimonial from "./Testimonial";
import styles from "./Testimonials.module.css";

const Testimonials: React.FC = () => {
	const elementWidth = 332;
	const [windowWidth, setWindowWidth] = useState(0);
	const [offset, setOffset] = useState(0);

	useEffect(() => {
		const handleResize = () => setWindowWidth(window.innerWidth);
		handleResize();
		window.addEventListener("resize", handleResize);
		return () => window.removeEventListener("resize", handleResize);
	}, []);

	const getNumToDisplay = () => {
		if (windowWidth > 1000) return 3;
		if (windowWidth > 680) return 2;
		return 1;
	};

	const numToDisplay = getNumToDisplay();
	const totalWidth = elementWidth * numToDisplay;
	const atStart = offset === 0;
	const atEnd = offset <= elementWidth * (testimonials.length - numToDisplay) * -1;

	const scroll = (direction: "left" | "right") => {
		if (direction === "left" && !atStart) {
			setOffset(offset + elementWidth);
		} else if (direction === "right" && !atEnd) {
			setOffset(offset - elementWidth);
		}
	};

	return (
		<section className={styles.section}>
			<h2>Detta säger tidigare kunder..</h2>
			<div className={styles.testimonialsContainer} style={{ width: `${totalWidth}px` }}>
				<div className={styles.testimonials} style={{ transform: `translateX(${offset}px)` }}>
					{testimonials.map((testimonial, index) => (
						<Testimonial key={index} testimonial={testimonial} />
					))}
				</div>
			</div>
			<div className={styles.buttons}>
				<button onClick={() => scroll("left")} disabled={atStart} aria-label="Föregående">
					<ChevronLeft />
					<span className={styles.screenReaderText}>Föregående</span>
				</button>
				<button onClick={() => scroll("right")} disabled={atEnd} aria-label="Nästa">
					<ChevronRight />
					<span className={styles.screenReaderText}>Nästa</span>
				</button>
			</div>
		</section>
	);
};

export default Testimonials;
