// src/pages/RevivalSuccessful/RevivalSuccessful.tsx
import React from "react";
import { Helmet } from "react-helmet-async";
import AboutMarkus from "../../components/Homepage/AboutMarkus";
import styles from "./RevivalSuccessful.module.css";

const RevivalSuccessful: React.FC = () => {
	return (
		<>
			<Helmet>
				<title>Grattis! Du är kvar på maillistan | Do things your way</title>
				<meta
					content="Du är kvar på maillistan och fortsätter få info och inspiration om stress och företagande"
					name="description"
				/>
			</Helmet>

			<main className={styles.main}>
				<h1>Grattis! 🎉</h1>
				<h2>
					Du är kvar på maillistan och fortsätter få info och inspiration om stress och företagande
				</h2>
			</main>
			<div id="about" className={styles.about}>
				<AboutMarkus />
			</div>
		</>
	);
};

export default RevivalSuccessful;

// src/routes/revivalsuccessful/index.svelte
<script>
	import Divider from "$lib/divider/Divider.svelte";
	import AboutMarkus from "$lib/homepage/about-markus/AboutMarkus.svelte";

</script>

<main>
	<h1>Grattis! 🎉</h1>
	<h2>Du är kvar på maillistan och fortsätter få info och inspiration om stress och företagande</h2>
</main>
<AboutMarkus/>

<style lang="scss">
	@use "../../styles/breakpoints.scss" as *;

	main {
		display: flex;
		flex-direction: column;
		align-items: center;
		max-width: 800px;
		margin: var(--spacing-xl) auto;
		padding: 0 100px;
		gap: var(--spacing-s);

		h1 {
			text-align: center;
			font-size: var(--font-size-xl);
			margin-bottom: var(--spacing-m);
		}

		h2 {
			width: 100%;
			text-align: center;
		}
	}
</style>
